name: 'Validate Gradle Wrapper'
on: [push, pull_request]

jobs:
    validation:
        name: 'Validation'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}
            - uses: gradle/actions/wrapper-validation@d156388eb19639ec20ade50009f3d199ce1e2808 # v4.1.0
